version: '3.8'

services:
  xavia-ota:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - BLOB_STORAGE_TYPE=local
      - DB_TYPE=supabase
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PRIVATE_KEY_BASE_64=${PRIVATE_KEY_BASE_64}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - HOST=${HOST}
      - SUPABASE_BUCKET_NAME=${SUPABASE_BUCKET_NAME}
      - LOG_LEVEL=info
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads:
    driver: local
